server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://47.121.188.34:3306/sg_blog
    username: root
    password: 15956501818xxy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
    host: 47.121.188.34
    # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password:
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8

mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
redis:
  host: 47.121.188.34
  port: 6379

oss:
  accessKey: KHXpvP7MH5Rhp7KHNqcmvYV6idycjnKz2EFRj7hG
  secretKey: X_seRlcbJoiMskBgPnCqEF-vfLICjy0xMvNznKtq
  bucket: xxyblog12138
